version: '3.7'

# networks:
#   bibapass_backend:
#     name: bibapass_backend
#     external: true
services:
  react:
    container_name: react
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    # networks:
      # - bibapass_backend
